from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes
import os

# קבלת הטוקן ממשתנה הסביבה
TOKEN = os.getenv("TOKEN")

# פונקציה שמגדירה את התגובה לפקודת /start
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    print("start command received")  # הדפסת הודעה ללוג
    await update.message.reply_text("שלום! אני כאן לעזור לך.")

# פונקציה שמגיבה לכל הודעת טקסט אחרת
async def echo(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    print("message received:", update.message.text)  # הדפסת הודעה ללוג
    text = update.message.text
    await update.message.reply_text(f"כתבת: {text}")

# הפונקציה הראשית שמריצה את הבוט
def main():
    print("Starting bot...")  # הודעה ללוג בתחילת ההפעלה
    application = Application.builder().token(TOKEN).build()

    # הוספת המאזין לפקודת /start
    application.add_handler(CommandHandler("start", start))
    print("Added start command handler")  # הודעה ללוג לאחר הוספת ה-handler

    # מאזין לכל הודעת טקסט
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, echo))
    print("Added message handler")  # הודעה ללוג לאחר הוספת ה-handler

    # הפעלת הבוט
    print("Running polling...")
    application.run_polling()

if __name__ == '__main__':
    main()
