from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes
import os

# קבלת הטוקן ממשתנה הסביבה
TOKEN = os.getenv("TOKEN")

# פונקציה שמגדירה את התגובה לפקודת /start
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    print("start command received")  # הדפסת הודעה ללוג
    await update.message.reply_text("שלום! אני כאן לעזור לך.")

# פונקציה שמגיבה לכל הודעת טקסט אחרת
async def echo(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    print("message received:", update.message.text)  # הדפסת הודעה ללוג
    text = update.message.text
    await update.message.reply_text(f"כתבת: {text}")

# הפונקציה הראשית שמריצה את הבוט
def main():
    print("Starting bot...")  # הודעה ללוג בתחילת ההפעלה
    application = Application.builder().token(TOKEN).build()

    # הוספת המאזין לפקודת /start
    application.add_handler(CommandHandler("start", start))
    print("Added start command handler")  # הודעה ללוג לאחר הוספת ה-handler

    # מאזין לכל הודעת טקסט
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, echo))
    print("Added message handler")  # הודעה ללוג לאחר הוספת ה-handler

    # הפעלת הבוט
    print("Running polling...")
    application.run_polling()

if __name__ == '__main__':
    main()

name: Run Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # הגבלת זמן ל-5 דקות

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install python-telegram-bot

    - name: Run bot
      env:
        TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        python bot.py

